name:                botReborn
version:             0.1.0.0
github:              "githubuser/botReborn"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

default-extensions:
- OverloadedStrings
- DeriveGeneric
- LambdaCase

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/botReborn#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - text
  - containers
  - bytestring
  - configurator
  - time
  - aeson
  - http-conduit

executables:
  botReborn-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - botReborn
    - text
    - bytestring
    - aeson
    - http-conduit

tests:
  botReborn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - botReborn
    - hspec
    - QuickCheck
    - text
    - mtl
    - containers
